src/Entity/Oauth/Client.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Oauth;

use FOS\OAuthServerBundle\Entity\Client as BaseClient;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use JMS\Serializer\Annotation as JMS;

/**
 * @ORM\Entity
 * @ORM\Table(name="oauth_client")
 */
class Client extends BaseClient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     *
     * @var string
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", nullable=true)
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(name="url", type="string", nullable=true)
     *
     * @var string
     */
    protected $url;

    /**
     * @ORM\OneToMany(targetEntity="User", mappedBy="application")
     *
     * @var Collection
     */
    protected $users;

    /**
     * @ORM\OneToMany(targetEntity="PiaApi\Entity\Oauth\AccessToken", mappedBy="client", cascade={"remove"})
     *
     * @JMS\Exclude()
     *
     * @var Collection
     */
    protected $tokens;

    public function __construct()
    {
        parent::__construct();

        $this->users = new ArrayCollection();
        $this->tokens = new ArrayCollection();
    }

    /**
     * {@inheritdoc}
     *
     * @fix FOS\OAuthServerBundle\Model\Client which concatenate id and random_id
     */
    public function getPublicId()
    {
        return $this->getRandomId();
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * @return Collection
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    /**
     * @param Collection $users
     */
    public function setUsers(Collection $users): void
    {
        $this->users = $users;
    }

    /**
     * @return Collection
     */
    public function getTokens(): Collection
    {
        return $this->tokens;
    }

    /**
     * @param Collection $tokens
     */
    public function setTokens(Collection $tokens): void
    {
        $this->tokens = $tokens;
    }

    public function getNotExpiredTokens()
    {
        return $this->tokens->filter(function (AccessToken $item) {
            return $item->getExpiresAt() >= (new \DateTime())->getTimestamp();
        });
    }
}

src/Entity/Pia/AbstractStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

abstract class AbstractStatus
{
    public const UNKNOWN = -1;

    protected const STATUS_NAME = [
        self::UNKNOWN             => 'UNKNOWN',
    ];

    protected static $statusNames = [];

    protected static function getNames()
    {
        $class = get_called_class();

        return self::STATUS_NAME + $class::$statusNames;
    }

    public static function isValid(int $status): bool
    {
        return isset(self::getNames()[$status]);
    }

    public static function getStatusName(int $status): string
    {
        if (!self::isValid($status)) {
            $status = self::UNKNOWN;
        }

        return self::getNames()[$status];
    }

    /**
     * @return int
     */
    public static function getStatusFromName(string $name): int
    {
        $status = self::UNKNOWN;
        $status_collection = array_flip(self::getNames());

        if (array_key_exists($name, $status_collection)) {
            $status = $status_collection[$name];
        }

        return $status;
    }
}

src/Entity/Pia/Answer.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_answer")
 */
class Answer implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="answers")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo = '';

    /**
     * @ORM\Column(type="json")
     * @JMS\Type("array")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var array
     */
    protected $data = [];

    public function getData(): array
    {
        return $this->data;
    }

    public function setData($data = [])
    {
        $this->data = $data;
    }

    public function getReferenceTo(): string
    {
        return $this->referenceTo;
    }

    public function setReferenceTo(string $ref)
    {
        $this->referenceTo = $ref;
    }
}

src/Entity/Pia/Attachment.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_attachment")
 */
class Attachment implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $mimeType;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="attachments")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="text")
     * @JMS\SerializedName("file")
     * @JMS\Accessor(setter="setFileFromBase64")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $attachmentFile;

    /**
     * @ORM\Column(type="boolean")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var bool
     */
    protected $piaSigned = false;

    public function setFileFromBase64(string $base64)
    {
        $parts = \explode(',', $base64);
        if (count($parts) > 1) {
            $this->attachmentFile = $parts[1];
        } else {
            $this->attachmentFile = $base64;
        }
    }
}

src/Entity/Pia/Comment.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_comment")
 */
class Comment implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="comments")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="text")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $description;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo;

    /**
     * @ORM\Column(type="boolean")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var bool
     */
    protected $forMeasure = false;
}

src/Entity/Pia/Evaluation.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use DateTime;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_evaluation")
 */
class Evaluation implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="evaluations")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="smallint")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var int
     */
    protected $status = 0;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $actionPlanComment;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $evaluationComment;

    /**
     * @ORM\Column(type="datetime")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var DateTime
     */
    protected $evaluationDate;

    /**
     * @ORM\Column(type="json")
     * @JMS\Type("array")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var array
     */
    protected $gauges;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var DateTime
     */
    protected $estimatedImplementationDate;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $personInCharge;

    /**
     * @ORM\Column(type="smallint")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var int
     */
    protected $globalStatus = 0;
}

src/Entity/Pia/Measure.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_measure")
 */
class Measure implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="measures")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $title;

    /**
     * @ORM\Column(type="text")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $content;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $placeholder;
}

src/Entity/Pia/PiaStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

class PiaStatus extends AbstractStatus
{
    public const IN_PROGRESS = 0;
    public const REFUSED = 1;
    public const SIMPLE_VALIDATION = 2;
    public const SIGNED_VALIDATION = 3;
    public const ARCHIVED = 4;
    public const WAITING_FOR_VALIDATION = 5;

    protected static $statusNames = [
        self::IN_PROGRESS             => 'IN_PROGRESS',
        self::REFUSED                 => 'REFUSED',
        self::SIMPLE_VALIDATION       => 'SIMPLE_VALIDATION',
        self::SIGNED_VALIDATION       => 'SIGNED_VALIDATION',
        self::ARCHIVED                => 'ARCHIVED',
        self::WAITING_FOR_VALIDATION  => 'WAITING_FOR_VALIDATION',
    ];
}

src/Entity/Pia/Portfolio.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Oauth\User;
use PiaApi\Entity\Pia\Traits\ResourceTrait;

/**
 * @ORM\Entity(repositoryClass="PiaApi\Repository\PortfolioRepository")
 * @ORM\Table(name="pia_portfolio")
 */
class Portfolio implements Timestampable
{
    use ResourceTrait,
        TimestampableEntity;

    /**
     * @ORM\Column(name="name", type="string", nullable=false)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\OneToMany(targetEntity="Structure", mappedBy="portfolio")
     * @JMS\MaxDepth(2)
     *
     * @var Collection
     */
    protected $structures;

    /**
     * @ORM\ManyToMany(targetEntity="PiaApi\Entity\Oauth\User", mappedBy="portfolios")
     * @JMS\Exclude()
     *
     * @var Collection
     */
    protected $users;

    public function __construct(string $name)
    {
        $this->name = $name;
        $this->structures = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    /**
     * @return array
     */
    public function getStructures(): array
    {
        return $this->structures->getValues();
    }

    /**
     * @return array
     */
    public function setStructures(iterable $structures): void
    {
        $this->structures->clear();

        foreach ($structures as $structure) {
            $this->addStructure($structure);
        }
    }

    public function addStructure(Structure $structure)
    {
        $structure->setPortfolio($this);
        $this->structures->add($structure);
    }

    public function removeStructure(Structure $structure)
    {
        $structure->setPortfolio(null);
        $this->structures->removeElement($structure);
    }

    /**
     * @return array
     */
    public function getUsers(): array
    {
        return $this->users->getValues();
    }

    public function setUsers(array $users): void
    {
        $this->users = new ArrayCollection($users);
    }

    public function addUser(User $user): void
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }
    }

    public function removeUser(User $user): array
    {
        $this->users->removeElement($user);
    }
}

src/Entity/Pia/ProcessingStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

class ProcessingStatus extends AbstractStatus
{
    public const STATUS_DOING = 0;
    public const STATUS_ARCHIVED = 1;

    protected static $statusNames = [
        self::STATUS_DOING      => 'STATUS_DOING',
        self::STATUS_ARCHIVED   => 'STATUS_ARCHIVED',
    ];
}

src/Entity/Pia/Traits/HasPiaTrait.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia\Traits;

use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Pia;

trait HasPiaTrait
{
    /**
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    public function getPia(): Pia
    {
        return $this->pia;
    }

    public function setPia(Pia $pia): void
    {
        $this->pia = $pia;
    }

    /**
     * @JMS\VirtualProperty("pia_id")
     */
    public function getPiaId()
    {
        return $this->pia->getId();
    }
}

templates/pia/Application/createForm.html.twig
{% trans_default_domain 'Pia' %}

{{ form_start(form) }}

{{ form_row(form.name) }}

{{ form_row(form.url) }}

{{ form_row(form.allowedGrantTypes) }}

<div class="required field">
    <a href="#" class="ui tiny primary button application-form-add-uri" data-list=".uri-fields-list" style="float:right;">
        <i class="plus icon"></i>
        {{ 'pia.actions.add'|trans }}
    </a>
    {{ form_label(form.redirectUris) }}

    <ul class="ui list uri-fields-list" data-prototype="{{ form_widget(form.redirectUris.vars.prototype)|e }}" data-widget-tags="{{ '<li class=" item"=" item""="item" ""></li>'|e }}">
    {% for uri in form.redirectUris %}
        <li class="item">
            {{ form_errors(uri) }}
            {{ form_widget(uri) }}
        </li>
    {% endfor %}
</ul>

</div>

{% do form.redirectUris.setRendered %}

<div class="ui divider"></div>

{{ form_rest(form) }}
{{ form_row(form.submit) }}

{{ form_end(form) }}

templates/pia/Application/manageApplications.html.twig
{% trans_default_domain 'Pia' %}

{% extends 'pia/Layout/base.html.twig' %}

{% import 'pia/Layout/_macros.html.twig' as macro %}

{% block title %}
    {{ 'pia.applications.title'|trans }}
{% endblock title %}

{% block navbar %}
    {% include 'pia/Layout/navbar.html.twig' with {
        'activeItem' : 'applications'
    } %}
{% endblock navbar %}

{% block body %}

    <div class="ui grid">

        <div class="twelve wide column">

            <div class="ui segment">

                <h2>
                    <a href="?limit=1000" class="ui tiny button" style="float:right;">{{ 'pia.actions.display'|trans }}
                        1000</a>
                    {{ 'pia.applications.title'|trans }}
                </h2>

                <div class="table responsive wrapper">
                    <table class="ui compact striped table">
                        <thead>
                            <tr>
                                <th>{{ 'pia.applications.list.id'|trans }}</th>
                                <th>{{ 'pia.applications.list.name'|trans }}</th>
                                <th>{{ 'pia.applications.list.url'|trans }}</th>
                                <th>{{ 'pia.applications.list.urls'|trans }}</th>
                                <th>{{ 'pia.applications.list.grant_types'|trans }}</th>
                                <th class="right aligned">
                                    <i class="cog icon"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for application in applications %}

                                {% set applicationInfos %}
                                <table class="ui striped table">
                                    <tbody>
                                        <tr>
                                            <td class="right aligned">
                                                <b>{{ 'pia.applications.list.client_id'|trans }}:</b>
                                            </td>
                                            <td>
                                                <span class="ui teal large label" style="font-family: Mono;">
                                                    {{ application.publicId }}
                                                </span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="right aligned">
                                                <b>{{ 'pia.applications.list.client_secret'|trans }}</b>
                                            </td>
                                            <td>
                                                <span class="ui teal large label" style="font-family: Mono;">
                                                    {{ application.secret }}
                                                </span>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                {% endset %}

                                <tr>
                                    <td>{{ application.id }}</td>
                                    <td>{{ application.name }}</td>
                                    <td>
                                        {% if application.url %}
                                            <a class="ui label" href="{{ application.url }}">
                                                {{ application.url }}
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% for url in application.redirectUris %}
                                            <span class="ui label">{{ url }}</span>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% for grantType in application.allowedGrantTypes %}
                                            <span class="ui label">{{ grantType }}</span>
                                        {% endfor %}
                                    </td>
                                    <td class="right aligned">
                                        <div class="ui small buttons">
                                            <a class="ui blue tiny icon button" data-popup="data-popup" data-html="{{ applicationInfos|e }}">
                                                <i class="key icon"></i>
                                            </a>
                                            <a class="ui green tiny icon button" title="{{ 'pia.actions.edit'|trans }}" data-modal="data-modal" href="{{ path('manage_applications_edit_application', {'applicationId':application.id}) }}">
                                                <i class="pencil icon"></i>
                                            </a>
                                            <a class="ui red tiny icon button" title="{{ 'pia.actions.remove'|trans }}" data-modal="data-modal" href="{{ path('manage_applications_remove_application', {'applicationId':application.id}) }}">
                                                <i class="trash icon"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
                {{ pagerfanta(applications, 'semantic_ui') }}
            </div>
        </div>

        <div class="four wide column">
            {% if is_granted('CAN_CREATE_APPLICATION') %}
                <div class="ui segment">

                    <h2>{{ 'pia.applications.add.title'|trans }}</h2>

                    {{ render(controller('PiaApi\\Controller\\BackOffice\\ApplicationController:addApplicationAction')) }}

                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>
        $(document).on('click', 'a[data-modal]', (e) => {
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();

            let button = $(e.currentTarget);
            let url = button.attr('href');

            let modal = $('.ui.modal');
            modal.hide();

            $.ajax({
                url: url,
                success: (html) => {
                    let modal = $('.ui.modal');

                    modal.find('.header').html(button.attr('title'));

                    modal
                        .find('.content')
                        .html(html);

                    modal.find('.content .negative, .content .deny, .content .cancel').on('click', (e) => {
                        $(e.currentTarget).closest('.ui.modal').modal('hide');
                    });

                    modal.find('.actions').remove();

                    $('.ui.checkbox').checkbox();
                    $('.ui.dropdown').dropdown();

                    modal.modal('show');
                }
            })
        });
    </script>

    <script>
        $(document).ready(() => {
            $(document).on('click', 'a.application-form-add-uri', (e) => {
                e.preventDefault();
                let list = $(e.currentTarget).closest('form').find($(e.currentTarget).attr('data-list'));

                let counter = list.data('widget-counter') | list.children().length;

                if (!counter) {
                    counter = list.children().length;
                }

                let newWidget = list.attr('data-prototype');
                newWidget = newWidget.replace(/__name__/g, counter);

                counter++;
                list.data(' widget-counter', counter);

                let newElem = $(list.attr('data-widget-tags')).html(newWidget);
                newElem.appendTo(list);
            });
        });
    </script>
{% endblock javascripts %}

templates/pia/Application/removeApplication.html.twig
{% trans_default_domain 'Pia' %}

{% set application = form.vars.value %}

<div class="ui negative message">
    <div class="ui clearing basic segment">
        <div class="header">
            {{ 'pia.applications.modals.remove.title'|trans }}
        </div>
        <i style="float:right;">{{ 'pia.applications.modals.remove.sub_title'|trans }}</i>
    </div>
</div>

<table class="ui single line table">
    <thead>
        <tr>
            <th colspan="100%">
                {{ 'pia.applications.modals.remove.resume.title'|trans }}
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="collapsing">
                <i class="user circle icon"></i>
                <b>{{ 'pia.applications.modals.remove.resume.name'|trans }}</b>
            </td>
            <td>{{ application.name }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="globe icon"></i>
                <b>{{ 'pia.applications.modals.remove.resume.url'|trans }}</b>
            </td>
            <td>{{ application.url }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="share square outline icon"></i>
                <b>{{ 'pia.applications.modals.remove.resume.urls'|trans }}</b>
            </td>
            <td>
                {% for redirectUri in application.redirectUris %}
                    <span class="ui label">{{ redirectUri }}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="envelope icon"></i>
                <b>{{ 'pia.applications.modals.remove.resume.user_number'|trans }}</b>
            </td>
            <td>{{ application.users|length }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="envelope icon"></i>
                <b>{{ 'pia.applications.modals.remove.resume.tokens'|trans }}</b>
            </td>
            <td>
                <span class="ui label">{{ application.tokens|length }}</span>
                {% set validtokens = application.getNotExpiredTokens() | length %}
                {% if validtokens > 0 %}
                    <span class="ui red label">
                        {{ validtokens }}&nbsp;{{ 'pia.applications.modals.remove.resume.currently_valid'|trans }}
                    </span>
                {% endif %}
            </td>
        </tr>
    </tbody>
</table>

{{ form_start(form) }}

{% do 
    form.submit.setRendered() %}

<input type="submit" class="ui fluid red button" value="{{ 'pia.actions.remove'|trans }}"/>

{{ form_end(form) }}