src/Entity/Pia/AbstractStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

abstract class AbstractStatus
{
    public const UNKNOWN = -1;

    protected const STATUS_NAME = [
        self::UNKNOWN             => 'UNKNOWN',
    ];

    protected static $statusNames = [];

    protected static function getNames()
    {
        $class = get_called_class();

        return self::STATUS_NAME + $class::$statusNames;
    }

    public static function isValid(int $status): bool
    {
        return isset(self::getNames()[$status]);
    }

    public static function getStatusName(int $status): string
    {
        if (!self::isValid($status)) {
            $status = self::UNKNOWN;
        }

        return self::getNames()[$status];
    }

    /**
     * @return int
     */
    public static function getStatusFromName(string $name): int
    {
        $status = self::UNKNOWN;
        $status_collection = array_flip(self::getNames());

        if (array_key_exists($name, $status_collection)) {
            $status = $status_collection[$name];
        }

        return $status;
    }
}

src/Entity/Pia/Answer.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_answer")
 */
class Answer implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="answers")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo = '';

    /**
     * @ORM\Column(type="json")
     * @JMS\Type("array")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var array
     */
    protected $data = [];

    public function getData(): array
    {
        return $this->data;
    }

    public function setData($data = [])
    {
        $this->data = $data;
    }

    public function getReferenceTo(): string
    {
        return $this->referenceTo;
    }

    public function setReferenceTo(string $ref)
    {
        $this->referenceTo = $ref;
    }
}

src/Entity/Pia/Attachment.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_attachment")
 */
class Attachment implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $mimeType;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="attachments")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="text")
     * @JMS\SerializedName("file")
     * @JMS\Accessor(setter="setFileFromBase64")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $attachmentFile;

    /**
     * @ORM\Column(type="boolean")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var bool
     */
    protected $piaSigned = false;

    public function setFileFromBase64(string $base64)
    {
        $parts = \explode(',', $base64);
        if (count($parts) > 1) {
            $this->attachmentFile = $parts[1];
        } else {
            $this->attachmentFile = $base64;
        }
    }
}

src/Entity/Pia/Comment.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_comment")
 */
class Comment implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="comments")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="text")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $description;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo;

    /**
     * @ORM\Column(type="boolean")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var bool
     */
    protected $forMeasure = false;
}

src/Entity/Pia/Evaluation.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use DateTime;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_evaluation")
 */
class Evaluation implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="evaluations")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="smallint")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var int
     */
    protected $status = 0;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $referenceTo;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $actionPlanComment;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $evaluationComment;

    /**
     * @ORM\Column(type="datetime")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var DateTime
     */
    protected $evaluationDate;

    /**
     * @ORM\Column(type="json")
     * @JMS\Type("array")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var array
     */
    protected $gauges;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var DateTime
     */
    protected $estimatedImplementationDate;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $personInCharge;

    /**
     * @ORM\Column(type="smallint")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var int
     */
    protected $globalStatus = 0;
}

src/Entity/Pia/Measure.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\HasPiaTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="pia_measure")
 */
class Measure implements Timestampable
{
    use ResourceTrait,
        HasPiaTrait,
        TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="Pia", inversedBy="measures")
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $title;

    /**
     * @ORM\Column(type="text")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $content;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $placeholder;
}

src/Entity/Pia/PiaStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

class PiaStatus extends AbstractStatus
{
    public const IN_PROGRESS = 0;
    public const REFUSED = 1;
    public const SIMPLE_VALIDATION = 2;
    public const SIGNED_VALIDATION = 3;
    public const ARCHIVED = 4;
    public const WAITING_FOR_VALIDATION = 5;

    protected static $statusNames = [
        self::IN_PROGRESS             => 'IN_PROGRESS',
        self::REFUSED                 => 'REFUSED',
        self::SIMPLE_VALIDATION       => 'SIMPLE_VALIDATION',
        self::SIGNED_VALIDATION       => 'SIGNED_VALIDATION',
        self::ARCHIVED                => 'ARCHIVED',
        self::WAITING_FOR_VALIDATION  => 'WAITING_FOR_VALIDATION',
    ];
}

src/Entity/Pia/ProcessingStatus.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

class ProcessingStatus extends AbstractStatus
{
    public const STATUS_DOING = 0;
    public const STATUS_ARCHIVED = 1;

    protected static $statusNames = [
        self::STATUS_DOING      => 'STATUS_DOING',
        self::STATUS_ARCHIVED   => 'STATUS_ARCHIVED',
    ];
}

src/Entity/Pia/Structure.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Traits\ResourceTrait;
use PiaApi\Entity\Pia\Traits\StructureInformationsTrait;

/**
 * @ORM\Entity(repositoryClass="PiaApi\Repository\StructureRepository")
 * @ORM\Table(name="pia_structure")
 */
class Structure implements Timestampable
{
    use ResourceTrait,
        TimestampableEntity,
        StructureInformationsTrait
    ;

    /**
     * @ORM\Column(name="name", type="string", nullable=false)
     * @JMS\Groups({"Default", "Export"})
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\ManyToOne(targetEntity="StructureType", inversedBy="structures", cascade={"persist"})
     * @JMS\Groups({"Default", "Export"})
     *
     * @var StructureType
     */
    protected $type;

    /**
     * @ORM\ManyToOne(targetEntity="Portfolio", inversedBy="structures", cascade={"persist"})
     * @JMS\Groups({"Default", "Export"})
     *
     * @var Portfolio
     */
    protected $portfolio;

    /**
     * @ORM\OneToMany(targetEntity="Pia", mappedBy="structure", cascade={"remove"})
     * @JMS\Exclude()
     *
     * @var Collection
     */
    protected $pias;

    /**
     * @ORM\OneToMany(targetEntity="PiaApi\Entity\Oauth\User", mappedBy="structure")
     * @JMS\Exclude()
     *
     * @var Collection
     */
    protected $users;

    /**
     * @ORM\ManyToMany(targetEntity="ProcessingTemplate", mappedBy="structures")
     * @JMS\Exclude()
     *
     * @var Collection
     */
    protected $templates;

    /**
     * @ORM\OneToMany(targetEntity="Folder", mappedBy="structure", cascade={"persist","remove"})
     * @JMS\Groups({"Full"})
     *
     * @var Collection
     */
    protected $folders;

    public function __construct(string $name)
    {
        $this->name = $name;

        $this->pias = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->templates = new ArrayCollection();
        $this->folders = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return Portfolio
     */
    public function getPortfolio(): ?Portfolio
    {
        return $this->portfolio;
    }

    /**
     * @param Portfolio $portfolio
     */
    public function setPortfolio(?Portfolio $portfolio): void
    {
        $this->portfolio = $portfolio;
    }

    /**
     * @deprecated since 1.4
     *
     * @return Collection
     */
    public function getPias(): Collection
    {
        return $this->pias;
    }

    /**
     * @deprecated since 1.4
     *
     * @param Collection $pias
     */
    public function setPias(Collection $pias): void
    {
        $this->pias = $pias;
    }

    /**
     * @return Collection
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    /**
     * @param Collection $users
     */
    public function setUsers(Collection $users): void
    {
        $this->users = $users;
    }

    /**
     * @return StructureType
     */
    public function getType(): ?StructureType
    {
        return $this->type;
    }

    /**
     * @param StructureType $type
     */
    public function setType(?StructureType $type): void
    {
        $this->type = $type;
    }

    /**
     * @return array|ProcessingTemplate[]
     */
    public function getTemplates(): array
    {
        return $this->templates->getValues();
    }

    /**
     * @param ProcessingTemplate $template
     *
     * @throws InvalidArgumentException
     */
    public function addTemplate(ProcessingTemplate $template): void
    {
        if ($this->templates->contains($template)) {
            throw new InvalidArgumentException(
                sprintf('The ProcessingTemplate « %s » is already allowed for Structure « %s »', $template->getName(), $this->name)
            );
        }
        $template->addStructure($this);
        $this->templates->add($template);
    }

    /**
     * @param ProcessingTemplate $template
     *
     * @throws InvalidArgumentException
     */
    public function removeTemplate(ProcessingTemplate $template): void
    {
        if (!$this->templates->contains($template)) {
            throw new InvalidArgumentException(
                sprintf('The ProcessingTemplate « %s » is not allowed for Structure « %s » and so cannot be disociated', $template->getName(), $this->name)
                );
        }
        $template->removeStructure($this);
        $this->templates->removeElement($template);
    }

    /**
     * @return Collection
     */
    public function getFolders(): Collection
    {
        return $this->folders;
    }

    /**
     * @param Collection $folders
     */
    public function setFolders(Collection $folders): void
    {
        $this->folders = $folders;
    }

    /**
     * @JMS\VirtualProperty
     * @JMS\SerializedName("rootFolder")
     * @JMS\Groups({"Default", "Export"})
     *
     * @return Folder
     */
    public function getRootFolder(): ?Folder
    {
        $roots = $this->folders->filter(function (Folder $folder) {
            return $folder->isRoot();
        });

        return $roots->count() > 0 ? $roots->first() : null;
    }

    /**
     * @return array
     */
    public function getProcessings()
    {
        return $this->getRootFolder()->flatCollectProcessings();
    }
}

src/Entity/Pia/Traits/HasPiaTrait.php
<?php

/*
 * Copyright (C) 2015-2018 Libre Informatique
 *
 * This file is licensed under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace PiaApi\Entity\Pia\Traits;

use JMS\Serializer\Annotation as JMS;
use PiaApi\Entity\Pia\Pia;

trait HasPiaTrait
{
    /**
     * @JMS\Exclude()
     *
     * @var Pia
     */
    protected $pia;

    public function getPia(): Pia
    {
        return $this->pia;
    }

    public function setPia(Pia $pia): void
    {
        $this->pia = $pia;
    }

    /**
     * @JMS\VirtualProperty("pia_id")
     */
    public function getPiaId()
    {
        return $this->pia->getId();
    }
}

templates/pia/Structure/manageStructures.html.twig
{% trans_default_domain 'Pia' %}

{% extends 'pia/Layout/base.html.twig' %}

{% import 'pia/Layout/_macros.html.twig' as macro %}

{% block title %}
    {{ 'pia.structures.title'|trans }}
{% endblock title %}

{% block navbar %}
    {% include 'pia/Layout/navbar.html.twig' with {
        'activeItem' : 'structures'
    } %}
{% endblock navbar %}

{% block body %}
    {% set cols = 2 %}
    {% set full = not is_granted('CAN_MANAGE_STRUCTURES') %}
    {% if not is_granted('CAN_SHOW_STRUCTURE')or not is_granted('CAN_SHOW_STRUCTURE_TYPE') %}
        {% set cols = 1 %}
    {% endif %}

    <div class="ui grid">

        <div class=" {{ full == true ? '' : 'twelve' }} wide column">

            <div class="ui grid">
                <div class="{{ cols == 2 ? 'ten' : 'sixteen' }} wide column">
                    {% if is_granted('CAN_SHOW_STRUCTURE') %}
                        {{ include('pia/Structure/partials/list.html.twig',{'structures':structures}) }}
                    {% endif %}
                </div>

                <div class="{{ cols == 2 ? 'six' : 'sixteen' }} wide column">
                    {% if is_granted('CAN_SHOW_STRUCTURE_TYPE') %}
                        {{ include('pia/StructureType/partials/list.html.twig',{'structureTypes':structureTypes}) }}
                    {% endif %}
                </div>
            </div>
        </div>

        {% if is_granted('CAN_MANAGE_STRUCTURES') and is_granted('CAN_MANAGE_STRUCTURE_TYPES')  %}
            <div class="four wide column">

                <div class="ui segment">

                    <h2>{{ 'pia.structures.add.title'|trans }}</h2>

                    {{ render(controller('PiaApi\\Controller\\BackOffice\\StructureController:addStructureAction')) }}

                </div>
                <div class="ui segment">

                    <h2>{{ 'pia.structure_types.add.title'|trans }}</h2>

                    {{ render(controller('PiaApi\\Controller\\BackOffice\\StructureController:addStructureTypeAction')) }}

                </div>

            </div>
        {% endif %}

    </div>

{% endblock %}

templates/pia/Structure/removeStructure.html.twig
{% trans_default_domain 'Pia' %}

{% set structure = form.vars.value %}

<div class="ui negative message">
    <div class="ui clearing basic segment">
        <div class="header">
            {{ 'pia.structures.modals.remove.title'|trans }}
        </div>
        <i style="float:right;">{{ 'pia.structures.modals.remove.sub_title'|trans }}</i>
    </div>
</div>

<table class="ui single line table">
    <thead>
        <tr>
            <th colspan="100%">
                {{ 'pia.structures.modals.remove.resume.structure'|trans }}
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="collapsing">
                <i class="building icon"></i>
                <b>{{ 'pia.structures.modals.remove.resume.name'|trans }}</b>
            </td>
            <td>{{ structure.name }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="users icon"></i>
                <b>{{ 'pia.structures.modals.remove.resume.users_number'|trans }}</b>
            </td>
            <td>{{ structure.users|length }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="folder open icon"></i>
                <b>{{ 'pia.structures.modals.remove.resume.processing_number'|trans }}</b>
            </td>
            <td>{{ structure.processings|length }}</td>
        </tr>
    </tbody>
</table>

{{ form_start(form) }}

{% do form.submit.setRendered() %}

<input type="submit" class="ui fluid red button" value="{{ 'pia.actions.remove'|trans }}"/>

{{ form_end(form) }}

templates/pia/Structure/removeStructureType.html.twig
{% trans_default_domain 'Pia' %}

{% set structureType = form.vars.value %}

<div class="ui negative message">
    <div class="ui clearing basic segment">
        <div class="header">
            {{ 'pia.structure_types.modals.remove.title'|trans }}
        </div>
        <i style="float:right;">{{ 'pia.structure_types.modals.remove.sub_title'|trans }}</i>
    </div>
</div>

<table class="ui single line table">
    <thead>
        <tr>
            <th colspan="100%">
                {{ 'pia.structure_types.modals.remove.resume.structure_type'|trans }}
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="collapsing">
                <i class="chevron right icon"></i>
                <b>{{ 'pia.structure_types.modals.remove.resume.name'|trans }}</b>
            </td>
            <td>{{ structureType.name }}</td>
        </tr>
        <tr>
            <td class="collapsing">
                <i class="building icon"></i>
                <b>{{ 'pia.structure_types.modals.remove.resume.structures_number'|trans }}</b>
            </td>
            <td>{{ structureType.structures|length }}</td>
        </tr>
    </tbody>
</table>

{{ form_start(form) }}

{% do form.submit.setRendered() %}

<input type="submit" class="ui fluid red button" value="{{ 'pia.actions.remove'|trans }}"/>

{{ form_end(form) }}

templates/pia/Structure/showStructure.html.twig
{% extends 'pia/Layout/base.html.twig' %}

{% import 'pia/Layout/_macros.html.twig' as macro %}

{% block title %}PIA User Management{% endblock title %}

{% block navbar %}
  {% include 'pia/Layout/navbar.html.twig' with {
    'activeItem' : 'my_structure'
  } %}
{% endblock navbar %}

{% block body %}

  <div class="ui grid">
    <div class="three wide column">
      <div class="ui segment">
        <h2>
          {{structure.name}}
          {% if structure.type is not null %}
            <br><small>({{structure.type.name}})</small>
          {% endif %}
        </h2>
      </div>
    </div>

    <div class="ten wide column">
      {{ include('pia/User/partials/list.html.twig',{'users':users}) }}
    </div>

    <div class="three wide column">
      <div class="ui segment">
        <h2>Ajouter un utilisateur</h2>
        {{ include('pia/Layout/form.html.twig',{'form':userForm}) }}


      </div>
    </div>
  </div>

{% endblock %}

{% block javascripts %}
  {{ parent() }}
{% endblock javascripts %}